name: misnap_flutter
description: A new Flutter plugin project.
version: 0.1.0
homepage: https://getperch.app

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: getperch.app.misnap_flutter
        pluginClass: MisnapFlutterPlugin
      ios:
        pluginClass: MisnapFlutterPlugin